### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by paulohlimamaia** [idemia/python-wsq#1] opened 2020-02-20 11:46 UTC
I do not know what i'm doing wrong but i'm always getting the error bellow when i try to open a .wsq image:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

my code is the following:

```
from PIL import Image
import wsq

img = Image('dig1.wsq')
```

I tried to build from this repository and also tried installing with pip

**Comment by paulohlimamaia** [comment] 2020-02-20 12:19
If I try to use the Image from inside the wsq module i get the following error:

```
wsq.WsqImagePlugin.Image.open('dig1.wsq')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'dig1.wsq'
```

**Comment by wajihullahbaig** [comment] 2020-03-24 07:53
@paulohlimamaia  Were you able to fix this?

**Comment by wajihullahbaig** [comment] 2020-03-24 07:56
Got it
You need the following line to open the wsq image
`    img = Image.open(file)`
Image(file) is incorrect in their readme snippet

**Comment by olivier-heurtier-ingroupe** [comment] 2020-04-20 19:58
Duplicate of #2

**Closed as completed** 2020-04-20 19:59 UTC
